# Laborator 3

Saptamana 11-15 martie 2019

## Exercitii simple folosind API de NumPy  

Nota: in rezolvarea exercitiilor se vor folosi cat mai mult functii NumPy vectorizate. Functiile scrise de voi vor fi documentate cu docstrings (tutoriale: Docstrings in Python, urmati NumPy Style Python Docstrings). Folositi type annotations. Utilizati doar pachetele NumPy si SciPy.

1. (0.5 puncte) Folosind functia `np.where`, determinati care sunt liniile si coloanele care contin un element dat intr-o matrice. 
1. (0.5 puncte) Pentru o matrice de numere, sa se determine produsul elementelor pe linii.
1. (0.5 puncte) Determinati daca toate elementele unei matrice `a` sunt mai mari sau egale decat toate de pe pozitiile corespondente din `b`.
1. (0.5 puncte) Pentru un vector de numere, care sunt *toate pozitiile* pe care apare valoarea maxima? Folositi functie NumPy.
1. (0.5 puncte) Se considera vectorul: `a = np.array([230, 10, 284, 39, 76])`. Folosind indexarea logica, sa se inmulteasca elementele din vector care sunt mai mici ca 100 cu 2 (restul raman neschimbate). Folosind ciclare, sa se aplice aceeasi operatie pana cand toate elementele devin mai mari ca 100. Sa se afiseze din vectorul final elementele care sunt mai mari de 150 si mai mici de 200.
1. (0.5 puncte) Sa se scrie o functie care preia doi vectori de aceeasi lungime si returneaza maximele pe pozitiile corespunzatoare:
```python
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b)
#iesire dorita: 
array([  4,   7,   9, 100, 300, 230,   3])
```
1. (1 punct) Sa se calculeze suma elementelor non-NaN intr-un 2d numpy array, in 3 feluri. Folosind comanda magica `%%timeit` [Built-in magic commands](http://ipython.readthedocs.io/en/stable/interactive/magics.html#cell-magics), [IPython Magic Commands](https://jakevdp.github.io/PythonDataScienceHandbook/01.03-magic-commands.html), sa se determine care e mai rapida.
    1. Peste o copie a tabelului initial (functia membru `copy()` a unui tablou) se suprascriu elementele nan cu 0, apoi se face suma;
    1. Folosind functia `np.nansum`;
    1. Folosind indiciere booleana si functia `np.isnan`, se determina colectia elementelor non-nan si se calculeaza suma lor in mod obisnuit.
1. (1 punct) Incarcati setul de date Iris, de la adresa 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', folosind `np.genfromtxt`.  Alegeti aleator 10 pozitii in matricea de 150 linii si 4 coloane (omiteti ultima coloana, de tip text), setati aceste valori pe NaN. Construiti o functie care, primid la intrare o matrice, returneaza un tuplu cu indicii de linie respectiv de coloana in care se gasesc valori NaN.
1. (1 punct) Construiti o functie care, primind o matrice, determina pe ce pozitii se afla valorile in afara unui interval \[min, max\] dat prin parametri. 
1. (1 punct) Sa se construiasca o functie care returneaza cele mai mari `k` valori dintr-un vector de cel putin `k` elemente, impreuna cu pozitiile lor. 

**Precizari:**
1. Se acorda 3 puncte din oficiu.
1. Tema se va prezenta in sapatamana 18-22 martie. 
1. Modalitatea de predare a temei: 
    1. se vor forma si se va lucra in echipe de cate doua persoane (in cazul in care nu se poate, se va lucra individual)
    2. exercitiile rezolvate se vor comite pe un repository **privat** de [Github](https://github.com/), la care vor avea doar acces membrii echipei si profesorii, Lucian Mircea Sasu (cont github: lmsasu) respectiv Arpad Kerestely (cont github: akerestely)
    3. repository-ul va contine un fisier "readme.md" (in radacina repository-ului) in care vor fi mentionati autorii temelor (cu nume complet)

In [8]:
import numpy as np

In [11]:
# Problem 1

def fun(matrix, element):
    """This function stores in the variable 'location', the lines and the columns where we can find the 'element'
        Parameters: matrix, element(the element searched)
        Return: Nothing"""
    
    location=np.where(matrix == element)
    print("Lines where the element is: ", list(location[0]))
    print("Columns where the element is: ",list(location[1]))
    
matrix: int= np.matrix([[1, 2, 3, 4], [5, 4, 7, 9],[9, 10, 11, 4], [4, 47, 9, 16]])
print(matrix)
fun(matrix, 9)

[[ 1  2  3  4]
 [ 5  4  7  9]
 [ 9 10 11  4]
 [ 4 47  9 16]]
Lines where the element is:  [1, 2, 3]
Columns where the element is:  [3, 0, 2]


In [15]:
# Problem 2

def fun(matrix):
    """This function stores in the variable 'matrix_transpose' the product of the initial matrix
        and after that the variable is transpose
        Parameters: matrix
        Return: The matrix transpose"""
    
    matrix_transpose=matrix.prod(axis=1)
    matrix_transpose.transpose()
    print("The product on lines:")
    return matrix_transpose

matrix: int = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8],[2, 4, 5, 10], [1, 2, 3, 4]])
print("Matrix: \n", matrix)
fun(matrix)

Matrix: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 2  4  5 10]
 [ 1  2  3  4]]
The product on lines:


matrix([[  24],
        [1680],
        [ 400],
        [  24]])

In [20]:
#Problem 3

def fun(matrix1, matrix2):
    """This function verify if all elements from a matrix are greater than the elements from another one. If is it will display a text
        Parameters: first matrix, second matrix
        Return: Nothing"""
    
    if(np.greater_equal(matrix1, matrix2).all()):
        print("All the elements from the first matrix are greater than the elements from the second matrix")
    else:
        print("Not all the elements from the first matrix are greater than the elements from the second matrix")
    
matrix1: int = np.array([[2, 3, 4, 5], [6, 7, 8 ,9 ],[10, 11, 12, 13], [13, 14, 15, 15]])
matrix2: int = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12], [13, 14, 15, 16]])
print(matrix1)
print(matrix2)
fun(matrix1, matrix2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [13 14 15 15]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Not all the elements from the first matrix are greater than the elements from the second matrix


In [19]:
# Problem 4 

def fun(array):
    """This function finds the maximum element in an array and print it with his indices
        Parameters: the array
        Return: Nothing"""
    
    maxElement: int = np.max(array)
    print("The max element is: ", maxElement)
    result = np.where(array == maxElement)
    print("Indices for the max element:", list(result[0]))
    
array: int = np.array([1,2,3,4,5,6,7,99,8,9,10,11,12,13,14,15,99,16,17,18,19,20])
fun(array)

The max element is:  99
Indices for the max element: [7, 16]


In [27]:
#Problem 5

def logic_indexing(arr):
    """This function multiply with 2 the elements from an array, that are greater than 100, using logic indexing.
        Parameters: the array
        Return: Nothing"""
    
    arr[arr < 100] *= 2
    print(("Logic indexing:\n"), list(arr))
    
def cycle(arr):
    """This function multiply with 2 the elements from an array while all the elements are greater than 100 and display the elements between 150 and 200.
        Parameters: the array
        Return: Nothing"""

    #arr1 = [i*2 if i < 100 else i for i in arr]
    while np.any(arr<100):
        arr[arr<100]*=2
    print("Cycle:\n", arr)
    print("Final elements:\n", arr[np.logical_and(arr>150, arr<200)])

arr: int = np.array([230, 10, 284, 39, 76])
print(list(arr))
logic_indexing(arr)
arr: int = np.array([230, 10, 284, 39, 76])
cycle(arr)

[230, 10, 284, 39, 76]
Logic indexing:
 [230, 20, 284, 78, 152]
Cycle:
 [230 160 284 156 152]
Final elements:
 [160 156 152]


In [29]:
#Problema 6

def pair_max(array1, array2):
    """This function implements 'maximum' from numpy and return maximum between 2 arrays
    Parameters: first array and the second array
    Return: an array with maximum"""
    
    return np.maximum(array1, array2)

a: int = np.array([3, 7, 9, 13, -10, 200, 3])
b: int = np.array([4, 5, -9, 100, 300, 230, 1])
rezultat = pair_max(a,b)
print(list(rezultat))

[4, 7, 9, 100, 300, 230, 3]


In [37]:
#Problema 7
#This program calculate the sum of non-Nan elements in 3 ways
import timeit

%time
matrix: int=np.array([[1, 2, 3],
        [np.nan,4 , 5],
        [np.nan, np.nan, 6]])
print(matrix)

def fun1():
    """This function copy the initial matrix and replace the values nan with 0. After that, calculate the sum
        Parameters: Nothing
        Return: Nothing"""
    copy: int=matrix.copy()
    copy[np.isnan(copy)]=0
    print(copy)
    print(copy.sum())
    
def fun2():
    """This function use a numpy function to calculate the sum"""
    return np.nansum(matrix)

def fun3():
    notNone: int=np.isnan(matrix)
    print(notNone)
    print(matrix2)
    
fun1()
fun2()
#fun3()

Wall time: 0 ns
[[ 1.  2.  3.]
 [nan  4.  5.]
 [nan nan  6.]]
21.0


21.0

In [40]:
#Problema 8
import random
from io import StringIO

def random_nan(data):
    """This function takes random indices from the matrix and replace the values with nan.
        Parameters: the matrix
        Return: Nothing"""
    for i in range(0, 10):
        random_index1 = np.random.randint(0, data.shape[0])
        random_index2 = np.random.randint(0, data.shape[1])
        data[random_index1, random_index2]=np.nan
    print(data)
    
def location_nan(data):
    """This function returns indices on lines and on columns for the nan values
        Parameters: data
        Return: 2 arrays with indices(lines and columns)"""
    location=np.where(np.isnan(data))
    return list(location[0]), list(location[1])

data: int=np.genfromtxt("iris.data.txt", delimiter=',', usecols=(0, 1, 2, 3))
data: int=np.array(data)
random_nan(data)
location_nan(data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [nan 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 nan 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

([40, 50, 81, 87, 99, 105, 109, 115, 130, 148], [0, 2, 1, 3, 0, 1, 0, 0, 0, 3])

In [39]:
#Problema 9

mat: int=np.array([[1,2,3,4],
              [3,5,2,7],
              [6,9,1,4],
              [3,8,1,7]])

def fun(min,max):
    """This function verify all the matrix's elements between an interval and returns 2 arrays with indices.
        Parameters: minimum and maximum for the interval
        Return: 2 arrays with indices(lines and columns)"""
    positions=np.where(np.logical_or(mat > max , mat < min))
    print(positions[0], positions[1])
    
fun(5,7)

[0 0 0 0 1 1 2 2 2 3 3 3] [0 1 2 3 0 2 1 2 3 0 1 2]


In [42]:
#Problema 10

def fun(n):
    """This function prints the number of maximum elements that is gived by parameter and their indices
        Parameters: the number of maximum elements
        Return: Nothing"""
    
    ind: int=np.argpartition(mat, -n)[-n:]
    print("Maximum:", mat[ind])
    print("Indices:", ind)
    
mat=np.array([1,2,3,4,5,6,95,8,9,10,97,12,13,98,15,16,17,18,99])
fun(4)

Maximum: [95 97 98 99]
Indices: [ 6 10 13 18]
