# Laborator 3

Saptamana 11-15 martie 2019

## Exercitii simple folosind API de NumPy  

Nota: in rezolvarea exercitiilor se vor folosi cat mai mult functii NumPy vectorizate. Functiile scrise de voi vor fi documentate cu docstrings (tutoriale: Docstrings in Python, urmati NumPy Style Python Docstrings). Folositi type annotations. Utilizati doar pachetele NumPy si SciPy.

1. (0.5 puncte) Folosind functia `np.where`, determinati care sunt liniile si coloanele care contin un element dat intr-o matrice. 
1. (0.5 puncte) Pentru o matrice de numere, sa se determine produsul elementelor pe linii.
1. (0.5 puncte) Determinati daca toate elementele unei matrice `a` sunt mai mari sau egale decat toate de pe pozitiile corespondente din `b`.
1. (0.5 puncte) Pentru un vector de numere, care sunt *toate pozitiile* pe care apare valoarea maxima? Folositi functie NumPy.
1. (0.5 puncte) Se considera vectorul: `a = np.array([230, 10, 284, 39, 76])`. Folosind indexarea logica, sa se inmulteasca elementele din vector care sunt mai mici ca 100 cu 2 (restul raman neschimbate). Folosind ciclare, sa se aplice aceeasi operatie pana cand toate elementele devin mai mari ca 100. Sa se afiseze din vectorul final elementele care sunt mai mari de 150 si mai mici de 200.
1. (0.5 puncte) Sa se scrie o functie care preia doi vectori de aceeasi lungime si returneaza maximele pe pozitiile corespunzatoare:
```python
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b)
#iesire dorita: 
array([  4,   7,   9, 100, 300, 230,   3])
```
1. (1 punct) Sa se calculeze suma elementelor non-NaN intr-un 2d numpy array, in 3 feluri. Folosind comanda magica `%%timeit` [Built-in magic commands](http://ipython.readthedocs.io/en/stable/interactive/magics.html#cell-magics), [IPython Magic Commands](https://jakevdp.github.io/PythonDataScienceHandbook/01.03-magic-commands.html), sa se determine care e mai rapida.
    1. Peste o copie a tabelului initial (functia membru `copy()` a unui tablou) se suprascriu elementele nan cu 0, apoi se face suma;
    1. Folosind functia `np.nansum`;
    1. Folosind indiciere booleana si functia `np.isnan`, se determina colectia elementelor non-nan si se calculeaza suma lor in mod obisnuit.
1. (1 punct) Incarcati setul de date Iris, de la adresa 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', folosind `np.genfromtxt`.  Alegeti aleator 10 pozitii in matricea de 150 linii si 4 coloane (omiteti ultima coloana, de tip text), setati aceste valori pe NaN. Construiti o functie care, primid la intrare o matrice, returneaza un tuplu cu indicii de linie respectiv de coloana in care se gasesc valori NaN.
1. (1 punct) Construiti o functie care, primind o matrice, determina pe ce pozitii se afla valorile in afara unui interval \[min, max\] dat prin parametri. 
1. (1 punct) Sa se construiasca o functie care returneaza cele mai mari `k` valori dintr-un vector de cel putin `k` elemente, impreuna cu pozitiile lor. 

**Precizari:**
1. Se acorda 3 puncte din oficiu.
1. Tema se va prezenta in sapatamana 18-22 martie. 
1. Modalitatea de predare a temei: 
    1. se vor forma si se va lucra in echipe de cate doua persoane (in cazul in care nu se poate, se va lucra individual)
    2. exercitiile rezolvate se vor comite pe un repository **privat** de [Github](https://github.com/), la care vor avea doar acces membrii echipei si profesorii, Lucian Mircea Sasu (cont github: lmsasu) respectiv Arpad Kerestely (cont github: akerestely)
    3. repository-ul va contine un fisier "readme.md" (in radacina repository-ului) in care vor fi mentionati autorii temelor (cu nume complet)

In [141]:
# Problema 1

import numpy as np
x = np.matrix([[1, 2, 3, 4], [5, 4, 7, 9],[9, 10, 11, 4], [4, 47, 15, 16]])
print(x)
element = 4
location=np.where(x == element)
print("Liniile pe care se afla numarul cautat sunt: ", list(location[0]))
print("Coloanele pe care se afla numarul cautat sunt: ",list(location[1]))

[[ 1  2  3  4]
 [ 5  4  7  9]
 [ 9 10 11  4]
 [ 4 47 15 16]]
Liniile pe care se afla numarul cautat sunt:  [0, 1, 2, 3]
Coloanele pe care se afla numarul cautat sunt:  [3, 1, 3, 0]


In [40]:
# Problema 2 - produsul pe linii al elementelor unei matrice

import numpy as np
from itertools import chain
x = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12], [13, 14, 15, 16]])
print("Matricea de numere este: \n", x)
print("Produsul pe linii al elementelor: \n", x.prod(axis=1))


Matricea de numere este: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Produsul pe linii al elementelor: 
 [[   24]
 [ 1680]
 [11880]
 [43680]]


In [123]:
#Problema 3

import numpy as np
matrix1 = np.array([[2, 3, 4, 5], [6, 7, 8 ,9 ],[10, 11, 12, 13], [13, 14, 15, 15]])
matrix2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12], [13, 14, 15, 16]])
print(matrix1)
print(matrix2)
print(np.greater_equal(matrix1,matrix2).all())
if(np.greater_equal(matrix1, matrix2).all()):
    print("Toate elementele matricei a sunt mai mari sau egale decat toate elementele matricei b")
else:
    print("Toate elementele matricei a nu sunt mai mari sau egale decat toate elementele matricei b")

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [13 14 15 15]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
False
Toate elementele matricei a nu sunt mai mari sau egale decat toate elementele matricei b


In [139]:
# Problema 4 

import numpy as np

array1 = np.array([1,2,3,4,5,6,7,99,8,9,10,11,12,13,14,15,99,16,17,18,19,20])
maxElement = np.amax(array1)
print("Elementul maxim este: ", maxElement)

rezultat = np.where(array1 == np.amax(array1))
print("Pozitiile unde se afla elementul maxim in vector sunt", list(rezultat[0]))

Elementul maxim este:  99
Pozitiile unde se afla elementul maxim in vector sunt [7, 16]


In [79]:
#Problema 5

import numpy as np
# indexare logica
arr = np.array([230, 10, 284, 39, 76])
print("Inainte de modificare vectorul este:\n", list(arr))

# daca elementul este mai mic ca 100 se inmulteste cu 2
arr[arr < 100] *= 2
print(("Dupa modificare vectorul este:\n"), list(arr))

#ciclare 
arr = np.array([230, 10, 284, 39, 76])
print("Inainte de modificare vectorul este:\n", list(arr))
arr1 = [i*2 if i < 100 else i for i in arr]
print(("Dupa modificare vectorul este:\n"), list(arr1))

Inainte de modificare vectorul este:
 [230, 10, 284, 39, 76]
Dupa modificare vectorul este:
 [230, 20, 284, 78, 152]
Inainte de modificare vectorul este:
 [230, 10, 284, 39, 76]
Dupa modificare vectorul este:
 [230, 20, 284, 78, 152]


In [65]:
#Problema 6
import numpy as np

def pair_max(array1, array2):
    return np.maximum(array1, array2)

a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
rezultat = np.array([None] * 10)
rezultat = pair_max(a,b)
rezultat1 = list(rezultat)
print(rezultat1)

[4, 7, 9, 100, 300, 230, 3]
